### ISSUE TITLE
(2) [ID] Posted and Closing dates are off by one

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#77] opened 2022-05-11 18:24 UTC

**Comment by mhuang-usdr** [comment] 2022-05-11 19:17
All Posted and Closing Dates on our tool is off-by-one from what's posted on Grants.gov.

Here's an example:

**Grants.gov:**
<img width="421" alt="image" src="https://user-images.githubusercontent.com/91221265/167928358-e960a2c5-ace3-40b3-8db2-0d1704795b39.png">

**USDR**
<img width="848" alt="image" src="https://user-images.githubusercontent.com/91221265/167928548-20691e35-f6c4-4859-999c-d145191f8691.png">

**Comment by mhuang-usdr** [comment] 2022-06-21 21:38
You can use this grant as an example:

- in USDR's tool - search for USDA-APHIS-10025-VSSP0000-23-0002
- Here's the direct link for [grants.gov](https://www.grants.gov/web/grants/view-opportunity.html?oppId=341188)

**Comment by anigonzales** [comment] 2022-06-22 18:29
Currently unable to reproduce issue; checked with multiple machines using different grant infos, and the dates match correctly on the app and the grants.gov

**Comment by mattbroussard** [comment] 2022-06-22 20:31
Right away from the description this smells to me like a timezone issue with things defaulting to UTC but then being displayed in local timezone.

It looks like the grantscraper gets a response from grants.gov that represents the date as a string, like `03/02/2022`. We then insert that directly into a postgres column of type `date`. It [appears](https://www.postgresql.org/docs/current/datatype-datetime.html) this is stored without any notion of timezone, so far so good.

Then on the query side, the server does not do anything to transform this field before sending to the client and it appears that the dates come out of Postgres as a JS `Date` object, which when stringified to JSON turns into `2022-03-02T00:00:00.000Z` (note this format now explicitly specifies UTC timezone). On the client, before being passed into `b-table` the dates are formatted with `new Date(grant.open_date).toLocaleDateString('en-US')` which formats a timestamp in local timezone and comes out as `3/1/2022` (since my local timezone is UTC-7).

This seems to be a common issue with knex + postgres and date columns. We can either configure knex to handle date values differently (see some examples of ways to do this in https://github.com/knex/knex/issues/3071) or add logic to `db.getGrants` to force these Date objects to a certain timezone, say EST.

**Comment by mhuang-usdr** [comment] 2022-07-11 16:17
@ajhyndman this seems very similar to the issue in the ARPA repo

**Comment by mattbroussard** [comment] 2022-08-27 01:27
Going to take this and probably apply my suggested fix above to make Knex return strings for `date` columns instead of `Date` objects. Need to do this as part of ARPA integration since such a change has already been made & is depended on in the arpa-reporter repo (see: https://github.com/usdigitalresponse/arpa-reporter/pull/440)

**Comment by mhuang-usdr** [comment] 2022-10-19 19:46
This is still an issue for me on `prod`.

I'm checking this use case:

- in USDR's tool - search for USDA-APHIS-10025-VSSP0000-23-0002. I see `Close Date` of `9/8/22`.
- Here's the direct link for [grants.gov](https://www.grants.gov/web/grants/view-opportunity.html?oppId=341188), which has a `Close Date` of `9/9/22`

**Comment by chrisxkeith** [comment] 2022-11-14 00:58
I believe this is because the grant “USDA-APHIS-10025-VSSP0000-23-0002” has not been synced from grants.gov since Matt applied his fix (merged into _staging [on Aug 30](https://github.com/usdigitalresponse/usdr-gost/pull/303#event-7289472423),  deployed September 15, 2022 at 10:27 AM). I will review a few grants with close dates around that date, and see if that pattern holds.

If so, this can be fixed by:
- First, we figure out how to fix https://github.com/usdigitalresponse/usdr-gost/issues/52
- Second, we increase GRANTS_SCRAPER_DATE_RANGE (even temporarily) to re-sync all old grants.

**Comment by chrisxkeith** [comment] 2022-11-14 21:48
I’m trying to sync the ‘USDA-APHIS-10025-VSSP0000-23-0002’ grant with my local database, but am not getting it. I’ve set GRANTS_SCRAPER_DATE_RANGE=120, which creates a date range back to the middle of July. Here are my assumptions:

- The date search range is based on grant close date.
- Having no keywords and checking all eligibility codes guarantees that all grants (within the date range) should be synced.

Are my assumptions wrong? If they are correct, does anyone have any idea why the grant ‘USDA-APHIS-10025-VSSP0000-23-0002’ isn’t being created in my local database?

**Comment by chrisxkeith** [comment] 2022-11-15 20:51
Default time zone of Postgresql is GMT (UTC), so days are shifted forward by one, assuming default time component of timestamp is midnight (which is usually considered part of the next day).

**Comment by chrisxkeith** [comment] 2022-11-15 23:04
This will fix all grants that will be synced (on the next sync cycle) after the code is deployed. It will not, however, fix grants that are too ‘old’ to be synced. I would like to do another set of code changes to address that which will:
- Change the sync cycle to once a day at 12:30am Eastern time
- Change GRANTS_SCRAPER_DATE_RANGE to 120 days (or more, if necessary). This will require manual editing of the .env files in _staging and production

Note that this should (I hope) also fix https://github.com/usdigitalresponse/usdr-gost/issues/52 . 

Actual fix is lines [10](https://github.com/usdigitalresponse/usdr-gost/blob/d8850abd3dd82adaed7b2c201c6cc647f3d7a4c5/packages/server/src/lib/grantscraper/index.js#L10) through [35](url). Other changes are to make the log entries more informative.

**Comment by as1729** [comment] 2022-11-22 18:41
https://www.loom.com/share/7fe40aa5db604da88785e054060e9bf0

Fix likely should be in how we transform this string into a date object in the front-end: https://github.com/usdigitalresponse/usdr-gost/blob/_staging/packages/client/src/components/GrantsTable.vue#L163

**Closed** 2023-01-10 19:21 UTC
Labels: bug, good first issue, ready for eng, ID Tool
