### ISSUE TITLE
[ARPA] Admin users should be able to download audit and treasury reports even when the reporting period is closed. 

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#1133] opened 2023-03-23 18:20 UTC

**Comment by TylerHendrickson** [comment] 2023-04-11 18:48
Intended: Admin users should always be able to download audit and treasury reports for any reporting cycle with information in it (i.e. previous, non-current cycles). Currently, when the reporting period is closed, the buttons don't appear and the UI says the reporting period is closed.

Open question: If we generate these reports using updated logic, it may mean that the output is different than it would have been had the report been generated during the actual reporting period. Is this acceptable? cc @jcomeau1

**Comment by mhuang-usdr** [comment] 2023-04-13 16:30
From conversation with ARPA partners:
- want to download the audit report as it would have been generated in the actual reporting period.

Solution suggestion:
- can we auto-generate an audit report when the period is closed, and make that available for future downloads

**Comment by as1729** [comment] 2023-11-03 14:25
This is a duplicate of #1801

**Closed by as1729** 2023-11-03 14:25 UTC
Labels: bug, ux goodness, arpa quarterly reporter
