### ISSUE TITLE
In My Grants - Cost Sharing dropdown cuts of 'Yes' & 'No' slightly

### ISSUE THREAD

**Issue by swatisqa1** [usdigitalresponse/usdr-gost#984] opened 2023-02-17 22:36 UTC
Env: Staging

Steps to Repro:
1. Navigate to My Grants tab
2. Click on 'Cost Sharing' drop down
3. Expected: See 'Yes' or 'No' fully visible

Actual: Yes is partially cut off - see image enclosed

![CostSharing](https://user-images.githubusercontent.com/123099222/219808172-09621c05-6096-440e-8936-130ab8c63478.png)

**Comment by as1729** [comment] 2023-02-17 22:40
Thanks for identifying and filing this bug! I'm going to move this to the project backlog.

**Comment by misspran** [comment] 2023-03-01 17:56
I think this might have been fixed? Or is it for specific screen sizes? Looks ok on my screen. 



![Image](https://user-images.githubusercontent.com/3173822/222222662-72a3e340-ccc5-4ec4-9ebf-a62ced013417.png)

**Comment by jakekreider** [comment] 2023-03-26 19:49
I can reproduce this locally if my (Chrome) window is < ~1300px wide, which shrinks the multiselect box and not leaving much room for the `:after` content (related https://github.com/shentao/vue-multiselect/issues/62). 
<img width="275" alt="image" src="https://user-images.githubusercontent.com/624510/227800015-72c5a80c-8780-4833-a0c8-109631374cd9.png">


I'll take this if no one else is on it. A few possible approaches here if a designer wants to weigh in:
1. Fix these multiselect fields to a larger minimum width to accommodate content & label. Will affect screen responsiveness.
2. Decrease the label padding to buy room down to a certain screen resolution (is there an official supported device width?)
3. Disable these "Press enter to select" labels altogether; I'm not sure they add anything with the highlight affordance (unless there are a11y implications I can't speak to)?

I'm new to the project & appreciate any guidance, thanks!

**Comment by mhuang-usdr** [comment] 2023-03-27 19:08
Welcome to the team! If you don't see anyone assigned to the ticket, feel free to take it!

I also highlighted this question in slack to see if one of our designers can jump in.

_Product context in case it's useful:_ our users exclusively use desktop computers, we don't have an official supported device width but we're designing with full monitors in mind.

**Comment by agn-dsgn** [comment] 2023-03-27 19:12
Hi! Volunteer designer here. My rec is to go with option 3 and remove the “Press enter to select” label! I rarely see this in dropdown fields, since the selection action is implied.

Slack discussion: https://usdigitalresponse.slack.com/archives/C0473BJ7HGE/p1679943934583849

**Comment by caitlinwinner** [comment] 2023-03-27 19:19
agree!

**Comment by jakekreider** [comment] 2023-03-27 19:54
Thanks all! I don't have rights to assign myself yet, but will put up a PR this evening for the fix.

**Closed** 2023-03-29 00:12 UTC
Labels: bug, good first issue
