### ISSUE TITLE
[ID] Rename "Agency" to "Team"

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#727] opened 2022-12-20 23:15 UTC
We found from talking with our partners that the term `Agency` didn't accurately reflect many of their use cases, and caused confusion. `Team` was more accurate.

This task is to update all instances of the word `Agency` or `Agencies` to `Team` or `Teams.` Here are two examples:

<img width="919" alt="image" src="https://user-images.githubusercontent.com/91221265/209215559-e49eab93-34ae-4a98-873a-d3f0c892df1b.png">

**Comment by mhuang-usdr** [comment] 2023-01-10 19:55
Waiting for FTE UXD's full redesign

**Comment by mhuang-usdr** [comment] 2023-01-10 22:15
A document from Pari detailing this further: https://docs.google.com/document/d/1Xqp6w-2WUBGErF_6npXhjAi04O56p2_h/edit

**Comment by LieAlbertTriAdrian** [comment] 2023-01-11 20:04
@mhuang-usdr Requested access to the docs to see whether I can help with that!

**Comment by ClaireValdivia** [comment] 2023-09-29 16:15
duplicate of #1846

**Closed** 2023-09-29 16:15 UTC
Labels: Grants Finder, ux goodness
