### ISSUE TITLE
[ARPA P&E Reporting] Ability to make some files invalid or indicate that it will not go to Treasury

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/usdr-gost#1346] opened 2023-05-09 19:02 UTC
**Submitted Description:**
this would be for admin users only, not regular agency users

**(Optional) Uploaded file - click to download:**

**Comment by as1729** [comment] 2023-05-15 19:57
Duplicate of #1268 

@jcomeau1 let me know if that is not the case and we need to re-open this.

**Closed by as1729** 2023-05-15 19:57 UTC
Labels: arpa quarterly reporter
