### ISSUE TITLE
[ID] I am unable to delete an Agency unless all keywords are deleted.

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#275] opened 2022-08-16 20:02 UTC
**Expected experience:** 
I can delete an agency regardless of if it still has keywords attached to it. 

**Actual experience:**

When I try to delete an agency with keywords, nothing happens after I click the delete button, and this error appears in the logs on Render:

`Aug 16 12:54:55 PM  server: error: delete from "agencies" where "id" = $1 and "parent" = $2 and "name" = $3 and "abbreviation" = $4 and "warning_threshold" = $5 and "danger_threshold" = $6 - update or delete on table "agencies" violates foreign key constraint "keywords_agency_id_foreign" on table "keywords"`

`

**Comment by mattbroussard** [comment] 2022-08-16 21:15
The obvious thing to do would be to add an `ON DELETE CASCADE` on the `keywords.agency_id` foreign key constraint. The other tables I could find* already do this for their `agency_id` FKs.

*with the exception of the `agencies` table itself, which has a self FK `parent`. What is the intended behavior for subagencies when deleting an agency? Should all subagencies be deleted, or should they become root agencies (i.e. `ON DELETE SET NULL`), or be re-parented to a different super-agency?

**Comment by mhuang-usdr** [comment] 2022-08-17 00:35
For now, the behavior is that user is not allowed to delete an agency with children. They need to first re-assign or delete the children before deleting the parent.

**Comment by mattbroussard** [comment] 2022-08-17 03:59
As far as I can tell, we do not enforce that in code now (other than implicitly with the non-cascading self-FK `agencies.parent -> agencies.id`). We should probably add that + appropriate error messaging alongside fixing this.

**Comment by chrisxkeith** [comment] 2022-12-06 00:03
@mhuang-usdr Where in the UI do I associate a keyword with an agency? I don't see anything in either the "Add Keyword" modal or "Edit Agency".  Thanks!

**Comment by mhuang-usdr** [comment] 2022-12-06 03:52
Any keyword added to the keyword page is automatically associated with the
agency the user is viewing.

**Comment by chrisxkeith** [comment] 2022-12-07 16:18
Test that I cannot get to run correctly:
```
4a5
> const knex = require('../../src/db/connection');
213a215,230
>         });
>     });
>     context('deleteAgency', () => {
>         it('deletes agency with keywords', async () => {
>             await knex(TABLES.agency_eligibility_codes)
>                 .where('agency_eligibility_codes.agency_id', fixtures.agencies.fleetServices.id)
>                 .del();
>             const del = await db.deleteAgency(
>                 fixtures.agencies.fleetServices.id,
>                 fixtures.agencies.fleetServices.parent,
>                 fixtures.agencies.fleetServices.name,
>                 fixtures.agencies.fleetServices.abbreviation,
>                 null,
>                 null,
>             );
>             expect(del).to.equal(1);
```

**Comment by chrisxkeith** [comment] 2023-01-02 21:18
Fixed with https://github.com/usdigitalresponse/usdr-gost/pull/679

**Closed by chrisxkeith** 2023-01-02 21:18 UTC
Labels: bug, good first issue, ready for eng, ID Tool, ux goodness
