### ISSUE TITLE
Ability to Archive/Exclude an upload from the Treasury export and Audit Report

### ISSUE THREAD

**Issue by jcomeau1** [usdigitalresponse/usdr-gost#1268] opened 2023-04-20 16:44 UTC
There are a number of cases where the partners will upload an Input Template, which is valid, but then they determine that it should NOT go to Treasury. Currently there is no mechanism to Archive or Exclude a specific uploaded (validated) file from going to Treasury. This extends to the Audit Report as well.

A couple of known reasons why this could happen:

1. The Admins wanted to test something either with the Reporter itself or with the Treasury Portal
2. An Agency uploaded the same Input Template twice, but used two different Agencies

The only option partners currently have is to manually edit the output files generated and we should guard against this. Additionally, once Input is validated, it will also be included in the Audit Reports

**Comment by jcomeau1** [comment] 2023-05-04 16:36
A potential concept for solving this issue would be to give the users (admins only?) the ability to invalidate a specific upload that previously validated:


![Image](https://user-images.githubusercontent.com/78866741/236268527-5a1d407a-5302-40af-ae00-d54f6b918165.png)

**Comment by mhuang-usdr** [comment] 2023-05-09 16:39
old ticket tracking this is #705

**Comment by as1729** [comment] 2023-05-11 16:34
Goal
- It should not be in the audit report
- It should not be included in the output template

What happens to the file?

Easier from technical aspect
- Delete? Make sure the partners are 100% aware

A bit more complex from design and eng aspect
- Archive? Lets understand the risks of keeping this file. How do we display it? How long do we hold onto the file.

Who can perform this action?
- All admins?
- USDR admins?
- The file uploader and admins?

**Comment by as1729** [comment] 2023-05-18 16:15
- Lean more towards the option of "archive/hide" rather than permanently deleting the workbook. (+2 votes)
- Technically the agencies should have this saved, but having the ability to look back is always helpful.
- Highest priority is to make sure it does not end up on the treasury report.
- It will be helpful to still see it in the uploads tab with the ability to have a toggle to show/hide.
- It should also not show up on the audit report as well.

**Comment by as1729** [comment] 2023-05-18 21:11
I believe @cajinajr is working on this. Can you confirm @caitlinwinner  so @jcomeau1 is aware who to reach out to?

**Comment by cajinajr** [comment] 2023-05-18 22:02
Confirmed. I am working on this ticket.

**Comment by cajinajr** [comment] 2023-06-07 20:55
@as1729 @mhuang-usdr - Work for this ticket ready for ENG review
[Link to Figma mockups](https://www.figma.com/file/3aIFGG3adqcoTc1ttDnB1R/ARPA---Editing-Workbook-Validation?type=design&node-id=191%3A793&t=czWByqMuzrG88AHe-1)
[Link to Notion 1 Pager](https://www.notion.so/usdr/Editing-validation-for-uploaded-workbooks-0bc8f91e19bf43bebf95bb26699354e3?pvs=4)

## Acceptance Criteria

- On the *Upload Details* page, add a section at the bottom of the details table and move all actions available to user there (download, validate, invalidate, and re-validate button styles outlined below)
- Remove yellow and green cell-shading from the details table
- Include the `check-lg` and `x-circle-fill` icons in the validation and invalidation timestamp message, respectively (refer to the [USDR design system](https://www.figma.com/file/HWu4iIjcoX2txuN543qzIB/USDR-Design-System?type=design&node-id=634%3A17346&t=gBQfcp5hsveBDgxV-1))

<img width="701" alt="Screen Shot 2023-06-07 at 4 42 24 PM" src="https://github.com/usdigitalresponse/usdr-gost/assets/16214088/2b1a2f5e-2cc1-4b48-ab6f-2f370504dd65">

### Download Button

- **Component:** Use the `button: primary` component
- **Visibility:** unchanged - visible to all users for every file that has been uploaded
- **Button text:** Download

### Validate Button

- **Component:** Use the `button: ghost` component
- **Visibility:** unchanged - visible to all users for every file that has been uploaded
- **Button text:** Validate

### Invalidate Button

- **Component:** Use the `button: ghost` component
- **Visibility:** only visible to admin users and only visible for workbook files that have *already been validated*
- **Button text:** Invalidate

### Re-validate Button

- **Component:** Use the `button: ghost` component
- **Visibility:** unchanged - visible to all users for workbook files that have *already been validated* OR *have failed validation*
- **Button text:** Re-validate

## Functionality

*Note:* only the functionality of the `invalidate` button is outlined here because the functionality of other buttons on the page will not change.

Once the invalidate button is clicked:

- A timestamp and the user responsible for the invalidation should be noted
  - in the “Validation” cell in the table on the *Upload Details* page
  - in the “Validation” column in the table list on the *Uploads* page

<img width="464" alt="Screen Shot 2023-06-07 at 4 50 36 PM" src="https://github.com/usdigitalresponse/usdr-gost/assets/16214088/ab590151-0910-4119-b954-b3bd278334c2">

<img width="333" alt="Screen Shot 2023-06-07 at 4 49 44 PM" src="https://github.com/usdigitalresponse/usdr-gost/assets/16214088/3fcb494e-d5fb-4b14-8c68-f9549c4c72c1">


- The invalidated workbook file should be excluded from the output files to Treasury and the Audit report
- If it exists, the previously validated file in that series of uploads (Agency and EC pairing) should be included instead
    - The inclusion of the previously validated file should be noted in the file’s series table on the *Upload Details* page

<img width="875" alt="Screen Shot 2023-06-07 at 4 46 58 PM" src="https://github.com/usdigitalresponse/usdr-gost/assets/16214088/bcc52a6e-aa18-47e6-9852-57fabf0b5551">

- If no previously validated file exists, the user should be notified that a validated upload doesn’t exist for that Agency and EC pairing

<img width="872" alt="Screen Shot 2023-06-07 at 4 47 09 PM" src="https://github.com/usdigitalresponse/usdr-gost/assets/16214088/0d40cd23-66ad-4cf0-b2f3-54932b2ac0cd">

**Comment by jcomeau1** [comment] 2023-06-15 21:01
We may need to create a new issue to address the near-term need of getting rid of the "invalid" uploads from the Q1 reporting period (must be completed by 6/23/23). The partners need to close out their last period to get the current period started. If we don't do the clean-up, the invalid uploads will be part of the audit report for every period going forward.

**Comment by tzinckgraf** [comment] 2023-06-19 01:59
@jcomeau1 can you send a screenshot of what these "invalid" uploads look like? Are there any examples on staging that I can look at?

**Comment by as1729** [comment] 2023-06-23 19:51
I was able to QA this endpoint in Staging and it works as intended.

**Comment by as1729** [comment] 2023-06-30 02:52
Moving this to in-progress since the front-end is still pending

**Closed** 2023-07-14 16:54 UTC
Labels: arpa quarterly reporter, arpa audit report, arpa output templates, 2Q23
