### ISSUE TITLE
Admins can administer all tenants, not just their own

### ISSUE THREAD

**Issue by cmroberts** [usdigitalresponse/usdr-gost#11] opened 2022-01-26 14:31 UTC
Currently permissioning doesn't take tenants into account - that needs to change! Verify that admins can only admin grants / users / etc within their own tenant.

**Comment by mhuang-usdr** [comment] 2022-03-24 18:15
See previous product discussions here: https://docs.google.com/document/d/1DG6YO0eiAiu9sFAsGjBQaCb1tGucmHkDsoB2i8OqCDU/edit#bookmark=id.60cjr2f8enx7

**Comment by mhuang-usdr** [comment] 2022-05-04 18:37
Closing this issue as a duplicate of #72.

**Closed by mhuang-usdr** 2022-05-04 18:37 UTC
Labels: bug, ready for eng
